default:
  SECRET_KEY: ""
  DEBUG: False
  ALLOWED_HOSTS: []
  DATABASE_URL: ""

heroku:
  DEBUG: False
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
    - password-generate.herokuapp.com

development:
  DEBUG: False
  ALLOWED_HOSTS:
    - 127.0.0.1
    - localhost
